import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        width: '95%',
        paddingHorizontal: 20,
        paddingVertical: 15,
        marginTop: 40,
        marginBottom: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    logoImage: {
        width: 36,
        height: 36,
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: '#FF6B6B',
        fontFamily: 'Inter_700Bold',
        letterSpacing: -0.5,
    },
    userSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    userProfile: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#F3F4F6',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    avatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#E5E7EB',
    },
    userName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        fontFamily: 'Inter_600SemiBold',
        maxWidth: 100,
    },
    logoutButton: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#FEF2F2',
    },
});
