import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    card: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 12,
        marginBottom: 16,
        alignItems: 'center',
        shadowColor: '#322e2b',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
    },
    cardWeb: {
        flexDirection: 'column',
        borderRadius: 32,
        padding: 0,
        height: 380,
        overflow: 'hidden',
        alignItems: 'stretch',
        shadowOpacity: 0.08,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 10 },
        borderTopLeftRadius: 48,
        borderBottomRightRadius: 48,
        borderTopRightRadius: 16,
        borderBottomLeftRadius: 16,
    },
    image: {
        width: 70,
        height: 70,
        borderRadius: 35,
        marginRight: 15,
    },
    imageWeb: {
        width: '100%',
        height: 200,
        borderRadius: 0,
        borderTopLeftRadius: 48,
        borderTopRightRadius: 16,
        marginRight: 0,
    },
    info: {
        flex: 1,
    },
    infoWeb: {
        padding: 24,
        flex: 1,
        justifyContent: 'space-between',
    },
    nombre: {
        fontSize: 18,
        fontWeight: '700',
        color: '#322e2b',
        fontFamily: 'Inter_700Bold',
        marginBottom: 4,
    },
    restaurante: {
        fontSize: 14,
        color: '#605a57',
        fontFamily: 'Inter_400Regular',
    },
    distancia: {
        fontSize: 14,
        color: '#605a57',
        fontFamily: 'Inter_400Regular',
        marginTop: 4,
    },
    boton: {
        backgroundColor: '#FF6B35',
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    botonWeb: {
        backgroundColor: '#FF6B35',
        borderRadius: 9999,
        paddingVertical: 12,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 16,
        alignSelf: 'flex-start',
    },
    botonWebTexto: {
        color: '#ffffff',
        fontFamily: 'Inter_700Bold',
        fontSize: 14,
    },
    botonIcono: {
        fontSize: 18,
    },
});
