import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');
const isWeb = Platform.OS === 'web';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FDFCFB', // Un blanco roto muy suave
    },
    loading: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    scrollContent: {
        paddingBottom: 100, // Espacio para el navbar flotante si existe
    },
    headerGradient: {
        paddingTop: 20,
        paddingBottom: 40,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
        backgroundColor: '#FFFFFF',
        shadowColor: '#FF6B35',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 20,
        elevation: 5,
    },
    welcomeSection: {
        marginTop: 10,
    },
    welcomeTitle: {
        fontSize: 28,
        fontWeight: '800',
        color: '#322E2B',
        letterSpacing: -0.5,
    },
    welcomeSubtitle: {
        fontSize: 16,
        color: '#8B7E74',
        marginTop: 6,
        fontWeight: '500',
        lineHeight: 22,
    },
    categoriesContainer: {
        marginTop: 30,
        paddingLeft: 20,
    },
    categoryPill: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        backgroundColor: '#FFFFFF',
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#F3F0EE',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 4,
        elevation: 2,
    },
    categoryPillActive: {
        backgroundColor: '#FF6B35',
        borderColor: '#FF6B35',
    },
    categoryText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#605A57',
    },
    categoryTextActive: {
        color: '#FFFFFF',
    },
    mainSection: {
        paddingHorizontal: 20,
        marginTop: 30,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: '700',
        color: '#322E2B',
    },
    seeAllText: {
        fontSize: 14,
        color: '#FF6B35',
        fontWeight: '600',
    },
    columnWrapper: {
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    card: {
        width: isWeb && width > 1024 ? '31%' : '48%',
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.06,
        shadowRadius: 12,
        elevation: 6,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#F8F5F2',
        overflow: 'hidden',
    },
    imageContainer: {
        width: '100%',
        height: 160,
        position: 'relative',
    },
    imageFixed: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    priceTag: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    priceText: {
        fontSize: 15,
        fontWeight: '800',
        color: '#FF6B35',
    },
    badge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: '#FFB800',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
    },
    badgeText: {
        fontSize: 10,
        fontWeight: '900',
        color: '#FFFFFF',
        textTransform: 'uppercase',
    },
    info: {
        padding: 16,
    },
    restaurant: {
        fontSize: 11,
        fontWeight: '700',
        color: '#FFB800',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 4,
    },
    nombre: {
        fontSize: 18,
        fontWeight: '700',
        color: '#322E2B',
        marginBottom: 6,
    },
    descripcion: {
        fontSize: 13,
        color: '#8B7E74',
        lineHeight: 18,
        marginBottom: 16,
    },
    cardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#FDFCFB',
        paddingTop: 12,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    ratingText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#322E2B',
    },
    botonAccion: {
        backgroundColor: '#FF6B35',
        width: 36,
        height: 36,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#FF6B35',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    emptyContainer: {
        padding: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    emptyIcon: {
        fontSize: 64,
        marginBottom: 20,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#322E2B',
        textAlign: 'center',
    },
    emptySub: {
        fontSize: 14,
        color: '#8B7E74',
        textAlign: 'center',
        marginTop: 10,
        lineHeight: 20,
    },
    featuredCard: {
        backgroundColor: '#322E2B',
        borderRadius: 28,
        padding: 24,
        marginBottom: 30,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.2,
        shadowRadius: 15,
        elevation: 10,
    },
    featuredInfo: {
        flex: 1,
        paddingRight: 20,
    },
    featuredBadge: {
        backgroundColor: 'rgba(255, 107, 53, 0.2)',
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
        marginBottom: 12,
    },
    featuredBadgeText: {
        color: '#FF6B35',
        fontSize: 12,
        fontWeight: '700',
    },
    featuredTitle: {
        fontSize: 22,
        fontWeight: '800',
        color: '#FFFFFF',
        marginBottom: 8,
    },
    featuredSub: {
        fontSize: 14,
        color: 'rgba(255,255,255,0.7)',
        lineHeight: 20,
    },
    featuredButton: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 16,
        marginTop: 16,
    },
    featuredButtonText: {
        color: '#322E2B',
        fontWeight: '700',
        fontSize: 14,
    }
});
