import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        width: '100%',
        height: '100%', // Usar el 100% del contenedor padre (cardsContainer)
        borderRadius: 32,
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#F3F0EE',
    },
    image: {
        width: '100%',
        height: '100%',
        position: 'absolute',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.3)',
    },
    gradient: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: '50%',
        justifyContent: 'flex-end',
        padding: 24,
    },
    infoContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 24,
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
    },
    badge: {
        position: 'absolute',
        top: 20,
        left: 20,
        backgroundColor: '#FF6B35',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },
    badgeText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '900',
        textTransform: 'uppercase',
    },
    priceTag: {
        position: 'absolute',
        top: 20,
        right: 20,
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 16,
    },
    priceText: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '800',
    },
    restaurant: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFB800',
        textTransform: 'uppercase',
        letterSpacing: 2,
        marginBottom: 8,
    },
    nombre: {
        fontSize: 28,
        fontWeight: '800',
        color: '#322E2B',
        marginBottom: 10,
    },
    descripcion: {
        fontSize: 15,
        color: '#605A57',
        lineHeight: 22,
        fontWeight: '400',
    },
    cardWrapper: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    }
});