import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        width: '95%',
        maxWidth: 1200,
        alignSelf: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginTop: 10,
        marginBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 24,
        shadowColor: '#110c0a',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.03,
        shadowRadius: 15,
        elevation: 5,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.02)',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    logoImage: {
        width: 36,
        height: 36,
    },
    title: {
        fontSize: 20,
        fontWeight: '800',
        color: '#FF6B35',
        fontFamily: 'Inter_800ExtraBold',
        letterSpacing: -0.6,
    },
    userSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
    },
    userProfile: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        backgroundColor: '#fef5f0',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 100,
        borderWidth: 1,
        borderColor: '#FFE5D9',
    },
    avatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#E5E7EB',
    },
    userName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        fontFamily: 'Inter_600SemiBold',
        maxWidth: 100,
    },
    logoutButton: {
        justifyContent: 'center',
        alignItems: 'center',
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#FEF2F2',
    },
});
